from modbus_client.gui.widgets.write_widgets.write_multiple_coils_widget import WriteMultipleCoilsWidget
from modbus_client.gui.widgets.write_widgets.write_multiple_registers_widget import WriteMultipleRegistersWidget
from modbus_client.gui.widgets.write_widgets.write_single_coil_widget import WriteSingleCoilWidget
from modbus_client.gui.widgets.write_widgets.write_single_register_widget import WriteSingleRegisterWidget