from enum import Enum


class Codes(Enum):
    WRITE_SINGLE_COIL = 5
    WRITE_SINGLE_REGISTER = 6
    WRITE_MULTIPLE_COILS = 15
    WRITE_MULTIPLE_REGISTERS = 16
    READ_COILS = 1
    READ_DISCRETE_INPUTS = 2
    READ_HOLDING_REGISTERS = 3
    READ_INPUT_REGISTERS = 4
    # READ_EXCEPTION_STATUS = '07'
    # DIAGNOSTICS = '08'


class ErrorCodes(Enum):
    READ_COILS = 129
    READ_DISCRETE_INPUTS = 130
    READ_HOLDING_REGISTERS = 131
    READ_INPUT_REGISTERS = 132
    WRITE_SINGLE_COIL = 133
    WRITE_SINGLE_REGISTER = 134
    WRITE_MULTIPLE_COILS = 135
    WRITE_MULTIPLE_REGISTERS = 136
